### ISSUE TITLE
Running the example script from npmjs.com returns error

### ISSUE THREAD

**Issue by chromium539** [murtajaziad/discord-tokens-checker#2]
```
      checker = new Checker("./output.txt");
                ^

TypeError: Checker is not a constructor
    at Object.<anonymous> (C:\Users\your user name\Desktop\tokens\index.js:2:17)
[90m    at Module._compile (internal/modules/cjs/loader.js:1158:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:1002:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:901:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)[39m
[90m    at internal/main/run_main_module.js:18:47[39m
```

**Comment by AnthonyCodeDev** [comment]
Yes :c
